In [13]:
import numpy as np
import re
from nltk.corpus import stopwords

In [3]:
def word_extraction(sentences):
    words = re.sub('[^\w]' , ' ' , sentences).split()
    cleaned_words = [w.lower() for w in words if w not in stopwords.words('english')]
    return cleaned_words

<>:2: SyntaxWarning: invalid escape sequence '\w'
<>:2: SyntaxWarning: invalid escape sequence '\w'
C:\Users\karan\AppData\Local\Temp\ipykernel_11020\2235359338.py:2: SyntaxWarning: invalid escape sequence '\w'
  words = re.sub('[^\w]' , ' ' , sentences).split()


In [4]:
def tokenize(sentences):
    words = []
    for sentence in sentences:
        w = word_extraction(sentence)
        words.extend(w)
        
    words = sorted(list(set(words)))
    return words

In [5]:
#test the prevoius two functions
text = "Ahmed and Ali arrived at the bus station early but waited until noon for the bus"

#word_extraction
word_extraction(text)

['ahmed', 'ali', 'arrived', 'bus', 'station', 'early', 'waited', 'noon', 'bus']

In [6]:
tokenize(word_extraction(text))

['ahmed', 'ali', 'arrived', 'bus', 'early', 'noon', 'station', 'waited']

In [11]:
def generate_bow(all_sentences):
    vocab = tokenize(all_sentences)
    print("The word list for the Document :\n{0}\n".format(vocab))
    
    for sentence in all_sentences:
        words = word_extraction(sentence)
        bow = np.zeros(len(vocab))
        
        for i, w in enumerate(vocab):
            for word in words:
                if word == w:
                    bow[i] += 1
                    
        print("The bag of words for the sentence :\n{0}\n{1}\n".format(sentence, np.array(bow)))
        print("-"*80)

In [12]:
all_sentences = ['Joe waited for the train',
                'The train was late',
                'Mary and Samantha took the bus',
                'I looked for Mary and Samantha at the bus station',
                'Mary and Samantha arrived at the bus station early but waited until noon for the bus']

generate_bow(all_sentences)

The word list for the Document :
['arrived', 'bus', 'early', 'i', 'joe', 'late', 'looked', 'mary', 'noon', 'samantha', 'station', 'the', 'took', 'train', 'waited']

The bag of words for the sentence :
Joe waited for the train
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]

--------------------------------------------------------------------------------
The bag of words for the sentence :
The train was late
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0.]

--------------------------------------------------------------------------------
The bag of words for the sentence :
Mary and Samantha took the bus
[0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0.]

--------------------------------------------------------------------------------
The bag of words for the sentence :
I looked for Mary and Samantha at the bus station
[0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0.]

--------------------------------------------------------------------------------
The bag of words for the sentence :
Mary and Saman